--------------------------------------------------------
-- Archivo creado  - domingo-mayo-17-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ACCESORIO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."ACCESORIO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CATEGORIA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."CATEGORIA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CLIENTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."CLIENTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DETALLE_CLIENTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."DETALLE_CLIENTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DETALLE_FACTURA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."DETALLE_FACTURA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DETALLE_MENU_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."DETALLE_MENU_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DETALLE_OC_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."DETALLE_OC_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DETALLE_PEDIDO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."DETALLE_PEDIDO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DETALLE_PRODUCTO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."DETALLE_PRODUCTO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMPLEADO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."EMPLEADO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMPRESA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."EMPRESA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ESTADO_HAB_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."ESTADO_HAB_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ESTADO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."ESTADO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence FACTURA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."FACTURA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence HAB_ACCESORIO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."HAB_ACCESORIO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence HABITACION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."HABITACION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence HOTEL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."HOTEL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence HOTEL_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."HOTEL_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence LOGIN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."LOGIN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence MENU_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."MENU_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ORDEN_COMPRA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."ORDEN_COMPRA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ORDEN_PEDIDO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."ORDEN_PEDIDO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PERFIL_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."PERFIL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PERIODO_MENU_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."PERIODO_MENU_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PRODUCTO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."PRODUCTO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence PROVEEDOR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."PROVEEDOR_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence RECEPCION_PEDIDO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."RECEPCION_PEDIDO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence RUBRO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."RUBRO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TIPO_CAMA_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."TIPO_CAMA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence TIPO_MENU_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOSTAL"."TIPO_MENU_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Table ACCESORIO
--------------------------------------------------------

  CREATE TABLE "HOSTAL"."ACCESORIO" 
   (	"ID_ACCESORIO" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CATEGORIA
--------------------------------------------------------

  CREATE TABLE "HOSTAL"."CATEGORIA" 
   (	"ID_CATEGORIA" NUMBER(10,0), 
	"DESCRIPCION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table CLIENTE
--------------------------------------------------------

  CREATE TABLE "HOSTAL"."CLIENTE" 
   (	"ID_CLIENTE" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"APELLIDO" VARCHAR2(30 BYTE), 
	"RUT" VARCHAR2(9 BYTE), 
	"TELEFONO" NUMBER(10,0), 
	"ID_EMPRESA" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DETALLE_CLIENTE
--------------------------------------------------------

  CREATE TABLE "HOSTAL"."DETALLE_CLIENTE" 
   (	"ID_DETALLE_CLIENTE" NUMBER(10,0), 
	"ID_CLIENTE" NUMBER(10,0), 
	"FECHA_INGRESO" DATE, 
	"FECHA_SALIDA" DATE, 
	"ID_HABITACION" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DETALLE_FACTURA
--------------------------------------------------------

  CREATE TABLE "HOSTAL"."DETALLE_FACTURA" 
   (	"ID_DETALLE_FACTURA" NUMBER(10,0), 
	"ID_DETALLE_CLIENTE" NUMBER(10,0), 
	"ID_FACTURA" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DETALLE_MENU
--------------------------------------------------------

  CREATE TABLE "HOSTAL"."DETALLE_MENU" 
   (	"ID_DETALLE_MENU" NUMBER(10,0), 
	"ID_DETALLE_CLIENTE" NUMBER(10,0), 
	"ID_MENU" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DETALLE_OC
--------------------------------------------------------

  CREATE TABLE "HOSTAL"."DETALLE_OC" 
   (	"ID_DETALLE_OC" NUMBER(10,0), 
	"DESCRIPCION" VARCHAR2(30 BYTE), 
	"ID_OC" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DETALLE_PEDIDO
--------------------------------------------------------

  CREATE TABLE "HOSTAL"."DETALLE_PEDIDO" 
   (	"ID_DETALLE_PEDIDO" NUMBER(10,0), 
	"ID_ORDEN_PEDIDO" NUMBER(10,0), 
	"ID_PRODUCTO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table DETALLE_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "HOSTAL"."DETALLE_PRODUCTO" 
   (	"ID_DETALLE_PRODUCTO" NUMBER(10,0), 
	"DESCRIPCION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPLEADO
--------------------------------------------------------

  CREATE TABLE "HOSTAL"."EMPLEADO" 
   (	"ID_EMPLEADO" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"APELLIDO" VARCHAR2(30 BYTE), 
	"RUT" VARCHAR2(9 BYTE), 
	"TELEFONO" NUMBER(10,0), 
	"MAIL" VARCHAR2(30 BYTE), 
	"ID_HOTEL" NUMBER(10,0), 
	"ID_USUARIO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EMPRESA
--------------------------------------------------------

  CREATE TABLE "HOSTAL"."EMPRESA" 
   (	"ID_EMPRESA" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"RUT" VARCHAR2(9 BYTE), 
	"DIRECCION" VARCHAR2(30 BYTE), 
	"TELEFONO" NUMBER(10,0), 
	"ID_USUARIO" NUMBER(10,0), 
	"ID_HOTEL" NUMBER(10,0), 
	"MAIL" VARCHAR2(20 BYTE), 
	"ACTIVO" CHAR(1 BYTE) DEFAULT 'Y'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ESTADO
--------------------------------------------------------

  CREATE TABLE "HOSTAL"."ESTADO" 
   (	"ID_ESTADO" NUMBER(10,0), 
	"CODIGO" VARCHAR2(5 BYTE), 
	"DESCRIPCION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ESTADO_HAB
--------------------------------------------------------

  CREATE TABLE "HOSTAL"."ESTADO_HAB" 
   (	"ID_ESTADO_HAB" NUMBER(10,0), 
	"DESCRIPCION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table FACTURA
--------------------------------------------------------

  CREATE TABLE "HOSTAL"."FACTURA" 
   (	"ID_FACTURA" NUMBER(10,0), 
	"ID_EMPRESA" NUMBER(10,0), 
	"FECHA_EMISION" DATE, 
	"FECHA_VENC" DATE, 
	"NETO" NUMBER(7,0), 
	"IVA" NUMBER(7,0), 
	"TOTAL" NUMBER(7,0), 
	"ID_ESTADO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HAB_ACCESORIO
--------------------------------------------------------

  CREATE TABLE "HOSTAL"."HAB_ACCESORIO" 
   (	"ID_HAB_ACCESORIO" NUMBER(10,0), 
	"ID_HABITACION" NUMBER(10,0), 
	"ID_ACCESORIO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HABITACION
--------------------------------------------------------

  CREATE TABLE "HOSTAL"."HABITACION" 
   (	"ID_HABITACION" NUMBER(10,0), 
	"ID_TIPO_CAMA" NUMBER(10,0), 
	"PRECIO" NUMBER(10,0), 
	"ID_ESTADO_HAB" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HOTEL
--------------------------------------------------------

  CREATE TABLE "HOSTAL"."HOTEL" 
   (	"ID_HOTEL" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(30 BYTE), 
	"RUT" VARCHAR2(9 BYTE), 
	"DIRECCION" VARCHAR2(30 BYTE), 
	"TELEFONO" NUMBER(10,0), 
	"MAIL" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table LOGIN
--------------------------------------------------------

  CREATE TABLE "HOSTAL"."LOGIN" 
   (	"ID_USUARIO" NUMBER(10,0), 
	"USERNAME" VARCHAR2(10 BYTE), 
	"PASSWORD" VARCHAR2(20 BYTE), 
	"ID_PERFIL" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table MENU
--------------------------------------------------------

  CREATE TABLE "HOSTAL"."MENU" 
   (	"ID_MENU" NUMBER(10,0), 
	"DESCRIPCION" VARCHAR2(30 BYTE), 
	"ID_TIPO_MENU" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORDEN_COMPRA
--------------------------------------------------------

  CREATE TABLE "HOSTAL"."ORDEN_COMPRA" 
   (	"ID_OC" NUMBER(10,0), 
	"FECHA_EMI" DATE, 
	"FECHA_VENC" DATE, 
	"NETO" NUMBER(7,0), 
	"IVA" NUMBER(7,0), 
	"TOTAL" NUMBER(7,0), 
	"ID_EMPRESA" NUMBER(10,0), 
	"ID_ESTADO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table ORDEN_PEDIDO
--------------------------------------------------------

  CREATE TABLE "HOSTAL"."ORDEN_PEDIDO" 
   (	"ID_ORDEN_PEDIDO" NUMBER(10,0), 
	"FECHA_PEDIDO" DATE, 
	"TOTAL" NUMBER(7,0), 
	"ID_PROVEEDOR" NUMBER(10,0), 
	"ID_EMPLEADO" NUMBER(10,0), 
	"ID_ESTADO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERFIL
--------------------------------------------------------

  CREATE TABLE "HOSTAL"."PERFIL" 
   (	"ID_PERFIL" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PERIODO_MENU
--------------------------------------------------------

  CREATE TABLE "HOSTAL"."PERIODO_MENU" 
   (	"ID_PERIODO_MENU" NUMBER(10,0), 
	"DESCRIPCION" VARCHAR2(20 BYTE), 
	"ID_MENU" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PRODUCTO
--------------------------------------------------------

  CREATE TABLE "HOSTAL"."PRODUCTO" 
   (	"ID_PRODUCTO" NUMBER(10,0), 
	"ID_CATEGORIA" NUMBER(10,0), 
	"ID_DETALLE_PRODUCTO" NUMBER(10,0), 
	"DESCRIPCION" VARCHAR2(20 BYTE), 
	"PRECIO" NUMBER(7,0), 
	"STOCK" NUMBER(7,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table PROVEEDOR
--------------------------------------------------------

  CREATE TABLE "HOSTAL"."PROVEEDOR" 
   (	"ID_PROVEEDOR" NUMBER(10,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"APELLIDO" VARCHAR2(20 BYTE), 
	"RUT" VARCHAR2(9 BYTE), 
	"TELEFONO" NUMBER(10,0), 
	"ID_RUBRO" NUMBER(10,0), 
	"ID_USUARIO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RECEPCION_PEDIDO
--------------------------------------------------------

  CREATE TABLE "HOSTAL"."RECEPCION_PEDIDO" 
   (	"ID_RECEPCION_PEDIDO" NUMBER(10,0), 
	"COD_PRODUCTO" NUMBER(10,0), 
	"ID_ORDEN_PEDIDO" NUMBER(10,0), 
	"FECHA_RECEPCION" DATE, 
	"ID_EMPLEADO" NUMBER(10,0), 
	"FECHA_VENC" NUMBER(8,0) DEFAULT 00000000
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table RUBRO
--------------------------------------------------------

  CREATE TABLE "HOSTAL"."RUBRO" 
   (	"ID_RUBRO" NUMBER(10,0), 
	"DESCRIPION" VARCHAR2(30 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TIPO_CAMA
--------------------------------------------------------

  CREATE TABLE "HOSTAL"."TIPO_CAMA" 
   (	"TIPO_CAMA" NUMBER(10,0), 
	"DESCRIPCION" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TIPO_MENU
--------------------------------------------------------

  CREATE TABLE "HOSTAL"."TIPO_MENU" 
   (	"ID_TIPO_MENU" NUMBER(10,0), 
	"DESCRIPCION" VARCHAR2(20 BYTE), 
	"PRECIO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into HOSTAL.ACCESORIO
SET DEFINE OFF;
REM INSERTING into HOSTAL.CATEGORIA
SET DEFINE OFF;
REM INSERTING into HOSTAL.CLIENTE
SET DEFINE OFF;
REM INSERTING into HOSTAL.DETALLE_CLIENTE
SET DEFINE OFF;
REM INSERTING into HOSTAL.DETALLE_FACTURA
SET DEFINE OFF;
REM INSERTING into HOSTAL.DETALLE_MENU
SET DEFINE OFF;
REM INSERTING into HOSTAL.DETALLE_OC
SET DEFINE OFF;
REM INSERTING into HOSTAL.DETALLE_PEDIDO
SET DEFINE OFF;
REM INSERTING into HOSTAL.DETALLE_PRODUCTO
SET DEFINE OFF;
REM INSERTING into HOSTAL.EMPLEADO
SET DEFINE OFF;
REM INSERTING into HOSTAL.EMPRESA
SET DEFINE OFF;
Insert into HOSTAL.EMPRESA (ID_EMPRESA,NOMBRE,RUT,DIRECCION,TELEFONO,ID_USUARIO,ID_HOTEL,MAIL,ACTIVO) values ('17','test','776665554','dir 123','123456','8','1','aa@ww.com','N');
REM INSERTING into HOSTAL.ESTADO
SET DEFINE OFF;
Insert into HOSTAL.ESTADO (ID_ESTADO,CODIGO,DESCRIPCION) values ('1','E','ACTIVA');
Insert into HOSTAL.ESTADO (ID_ESTADO,CODIGO,DESCRIPCION) values ('2','E','INACTIVA');
REM INSERTING into HOSTAL.ESTADO_HAB
SET DEFINE OFF;
REM INSERTING into HOSTAL.FACTURA
SET DEFINE OFF;
REM INSERTING into HOSTAL.HAB_ACCESORIO
SET DEFINE OFF;
REM INSERTING into HOSTAL.HABITACION
SET DEFINE OFF;
REM INSERTING into HOSTAL.HOTEL
SET DEFINE OFF;
Insert into HOSTAL.HOTEL (ID_HOTEL,NOMBRE,RUT,DIRECCION,TELEFONO,MAIL) values ('1','clarita','776665554','clarita 123','1234567','clarita123@test.com');
REM INSERTING into HOSTAL.LOGIN
SET DEFINE OFF;
Insert into HOSTAL.LOGIN (ID_USUARIO,USERNAME,PASSWORD,ID_PERFIL) values ('8','pepito','pp123','2');
REM INSERTING into HOSTAL.MENU
SET DEFINE OFF;
REM INSERTING into HOSTAL.ORDEN_COMPRA
SET DEFINE OFF;
REM INSERTING into HOSTAL.ORDEN_PEDIDO
SET DEFINE OFF;
REM INSERTING into HOSTAL.PERFIL
SET DEFINE OFF;
Insert into HOSTAL.PERFIL (ID_PERFIL,NOMBRE) values ('1','admin');
Insert into HOSTAL.PERFIL (ID_PERFIL,NOMBRE) values ('2','empresa');
REM INSERTING into HOSTAL.PERIODO_MENU
SET DEFINE OFF;
REM INSERTING into HOSTAL.PRODUCTO
SET DEFINE OFF;
REM INSERTING into HOSTAL.PROVEEDOR
SET DEFINE OFF;
REM INSERTING into HOSTAL.RECEPCION_PEDIDO
SET DEFINE OFF;
REM INSERTING into HOSTAL.RUBRO
SET DEFINE OFF;
REM INSERTING into HOSTAL.TIPO_CAMA
SET DEFINE OFF;
REM INSERTING into HOSTAL.TIPO_MENU
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index RECEPCION_PEDIDO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."RECEPCION_PEDIDO_PK" ON "HOSTAL"."RECEPCION_PEDIDO" ("ID_RECEPCION_PEDIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TIPO_CAMA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."TIPO_CAMA_PK" ON "HOSTAL"."TIPO_CAMA" ("TIPO_CAMA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index LOGIN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."LOGIN_PK" ON "HOSTAL"."LOGIN" ("ID_USUARIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERIODO_MENU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."PERIODO_MENU_PK" ON "HOSTAL"."PERIODO_MENU" ("ID_PERIODO_MENU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ESTADO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."ESTADO_PK" ON "HOSTAL"."ESTADO" ("ID_ESTADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index RUBRO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."RUBRO_PK" ON "HOSTAL"."RUBRO" ("ID_RUBRO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CLIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."CLIENTE_PK" ON "HOSTAL"."CLIENTE" ("ID_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DETALLE_FACTURA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."DETALLE_FACTURA_PK" ON "HOSTAL"."DETALLE_FACTURA" ("ID_DETALLE_FACTURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DETALLE_CLIENTE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."DETALLE_CLIENTE_PK" ON "HOSTAL"."DETALLE_CLIENTE" ("ID_DETALLE_CLIENTE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ACCESORIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."ACCESORIO_PK" ON "HOSTAL"."ACCESORIO" ("ID_ACCESORIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ORDEN_COMPRA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."ORDEN_COMPRA_PK" ON "HOSTAL"."ORDEN_COMPRA" ("ID_OC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index HABITACION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."HABITACION_PK" ON "HOSTAL"."HABITACION" ("ID_HABITACION") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ESTADO_HAB_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."ESTADO_HAB_PK" ON "HOSTAL"."ESTADO_HAB" ("ID_ESTADO_HAB") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DETALLE_PRODUCTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."DETALLE_PRODUCTO_PK" ON "HOSTAL"."DETALLE_PRODUCTO" ("ID_DETALLE_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index MENU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."MENU_PK" ON "HOSTAL"."MENU" ("ID_MENU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index HAB_ACCESORIO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."HAB_ACCESORIO_PK" ON "HOSTAL"."HAB_ACCESORIO" ("ID_HAB_ACCESORIO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPRESA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."EMPRESA_PK" ON "HOSTAL"."EMPRESA" ("ID_EMPRESA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DETALLE_PEDIDO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."DETALLE_PEDIDO_PK" ON "HOSTAL"."DETALLE_PEDIDO" ("ID_DETALLE_PEDIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index FACTURA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."FACTURA_PK" ON "HOSTAL"."FACTURA" ("ID_FACTURA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DETALLE_OC_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."DETALLE_OC_PK" ON "HOSTAL"."DETALLE_OC" ("ID_DETALLE_OC") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index CATEGORIA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."CATEGORIA_PK" ON "HOSTAL"."CATEGORIA" ("ID_CATEGORIA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index UNIQUE_CONSTRAINT_USERNAME
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."UNIQUE_CONSTRAINT_USERNAME" ON "HOSTAL"."LOGIN" ("USERNAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index HOTEL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."HOTEL_PK" ON "HOSTAL"."HOTEL" ("ID_HOTEL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index ORDEN_PEDIDO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."ORDEN_PEDIDO_PK" ON "HOSTAL"."ORDEN_PEDIDO" ("ID_ORDEN_PEDIDO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PROVEEDOR_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."PROVEEDOR_PK" ON "HOSTAL"."PROVEEDOR" ("ID_PROVEEDOR") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index TIPO_MENU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."TIPO_MENU_PK" ON "HOSTAL"."TIPO_MENU" ("ID_TIPO_MENU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PERFIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."PERFIL_PK" ON "HOSTAL"."PERFIL" ("ID_PERFIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index DETALLE_MENU_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."DETALLE_MENU_PK" ON "HOSTAL"."DETALLE_MENU" ("ID_DETALLE_MENU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index EMPLEADO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."EMPLEADO_PK" ON "HOSTAL"."EMPLEADO" ("ID_EMPLEADO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index PRODUCTO_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HOSTAL"."PRODUCTO_PK" ON "HOSTAL"."PRODUCTO" ("ID_PRODUCTO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table TIPO_MENU
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."TIPO_MENU" ADD CONSTRAINT "TIPO_MENU_PK" PRIMARY KEY ("ID_TIPO_MENU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSTAL"."TIPO_MENU" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."TIPO_MENU" MODIFY ("ID_TIPO_MENU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."EMPLEADO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."EMPLEADO" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."EMPLEADO" MODIFY ("ID_HOTEL" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."EMPLEADO" MODIFY ("MAIL" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."EMPLEADO" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."EMPLEADO" MODIFY ("RUT" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."EMPLEADO" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."EMPLEADO" ADD CONSTRAINT "EMPLEADO_PK" PRIMARY KEY ("ID_EMPLEADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSTAL"."EMPLEADO" MODIFY ("ID_EMPLEADO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DETALLE_PEDIDO
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."DETALLE_PEDIDO" ADD CONSTRAINT "DETALLE_PEDIDO_PK" PRIMARY KEY ("ID_DETALLE_PEDIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSTAL"."DETALLE_PEDIDO" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."DETALLE_PEDIDO" MODIFY ("ID_ORDEN_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."DETALLE_PEDIDO" MODIFY ("ID_DETALLE_PEDIDO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table FACTURA
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."FACTURA" ADD CONSTRAINT "FACTURA_PK" PRIMARY KEY ("ID_FACTURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSTAL"."FACTURA" MODIFY ("TOTAL" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."FACTURA" MODIFY ("IVA" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."FACTURA" MODIFY ("NETO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."FACTURA" MODIFY ("FECHA_VENC" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."FACTURA" MODIFY ("FECHA_EMISION" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."FACTURA" MODIFY ("ID_EMPRESA" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."FACTURA" MODIFY ("ID_FACTURA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDEN_COMPRA
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."ORDEN_COMPRA" ADD CONSTRAINT "ORDEN_COMPRA_PK" PRIMARY KEY ("ID_OC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSTAL"."ORDEN_COMPRA" MODIFY ("ID_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."ORDEN_COMPRA" MODIFY ("ID_EMPRESA" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."ORDEN_COMPRA" MODIFY ("TOTAL" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."ORDEN_COMPRA" MODIFY ("IVA" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."ORDEN_COMPRA" MODIFY ("NETO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."ORDEN_COMPRA" MODIFY ("FECHA_VENC" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."ORDEN_COMPRA" MODIFY ("FECHA_EMI" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."ORDEN_COMPRA" MODIFY ("ID_OC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DETALLE_FACTURA
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."DETALLE_FACTURA" ADD CONSTRAINT "DETALLE_FACTURA_PK" PRIMARY KEY ("ID_DETALLE_FACTURA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSTAL"."DETALLE_FACTURA" MODIFY ("ID_FACTURA" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."DETALLE_FACTURA" MODIFY ("ID_DETALLE_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."DETALLE_FACTURA" MODIFY ("ID_DETALLE_FACTURA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DETALLE_CLIENTE
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."DETALLE_CLIENTE" ADD CONSTRAINT "DETALLE_CLIENTE_PK" PRIMARY KEY ("ID_DETALLE_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSTAL"."DETALLE_CLIENTE" MODIFY ("ID_HABITACION" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."DETALLE_CLIENTE" MODIFY ("FECHA_SALIDA" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."DETALLE_CLIENTE" MODIFY ("FECHA_INGRESO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."DETALLE_CLIENTE" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."DETALLE_CLIENTE" MODIFY ("ID_DETALLE_CLIENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ORDEN_PEDIDO
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."ORDEN_PEDIDO" ADD CONSTRAINT "ORDEN_PEDIDO_PK" PRIMARY KEY ("ID_ORDEN_PEDIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSTAL"."ORDEN_PEDIDO" MODIFY ("ID_ESTADO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."ORDEN_PEDIDO" MODIFY ("ID_EMPLEADO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."ORDEN_PEDIDO" MODIFY ("ID_PROVEEDOR" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."ORDEN_PEDIDO" MODIFY ("TOTAL" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."ORDEN_PEDIDO" MODIFY ("FECHA_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."ORDEN_PEDIDO" MODIFY ("ID_ORDEN_PEDIDO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HAB_ACCESORIO
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."HAB_ACCESORIO" ADD CONSTRAINT "HAB_ACCESORIO_PK" PRIMARY KEY ("ID_HAB_ACCESORIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSTAL"."HAB_ACCESORIO" MODIFY ("ID_ACCESORIO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."HAB_ACCESORIO" MODIFY ("ID_HABITACION" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."HAB_ACCESORIO" MODIFY ("ID_HAB_ACCESORIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RECEPCION_PEDIDO
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."RECEPCION_PEDIDO" ADD CONSTRAINT "RECEPCION_PEDIDO_PK" PRIMARY KEY ("ID_RECEPCION_PEDIDO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSTAL"."RECEPCION_PEDIDO" MODIFY ("ID_EMPLEADO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."RECEPCION_PEDIDO" MODIFY ("FECHA_RECEPCION" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."RECEPCION_PEDIDO" MODIFY ("ID_ORDEN_PEDIDO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."RECEPCION_PEDIDO" MODIFY ("COD_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."RECEPCION_PEDIDO" MODIFY ("ID_RECEPCION_PEDIDO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTADO
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."ESTADO" ADD CONSTRAINT "ESTADO_PK" PRIMARY KEY ("ID_ESTADO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSTAL"."ESTADO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."ESTADO" MODIFY ("CODIGO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."ESTADO" MODIFY ("ID_ESTADO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."MENU" ADD CONSTRAINT "MENU_PK" PRIMARY KEY ("ID_MENU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSTAL"."MENU" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."MENU" MODIFY ("ID_MENU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ESTADO_HAB
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."ESTADO_HAB" ADD CONSTRAINT "ESTADO_HAB_PK" PRIMARY KEY ("ID_ESTADO_HAB")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSTAL"."ESTADO_HAB" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."ESTADO_HAB" MODIFY ("ID_ESTADO_HAB" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."CLIENTE" ADD CONSTRAINT "CLIENTE_PK" PRIMARY KEY ("ID_CLIENTE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSTAL"."CLIENTE" MODIFY ("ID_EMPRESA" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."CLIENTE" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."CLIENTE" MODIFY ("RUT" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."CLIENTE" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."CLIENTE" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."CLIENTE" MODIFY ("ID_CLIENTE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CATEGORIA
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."CATEGORIA" ADD CONSTRAINT "CATEGORIA_PK" PRIMARY KEY ("ID_CATEGORIA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSTAL"."CATEGORIA" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."CATEGORIA" MODIFY ("ID_CATEGORIA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DETALLE_OC
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."DETALLE_OC" ADD CONSTRAINT "DETALLE_OC_PK" PRIMARY KEY ("ID_DETALLE_OC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSTAL"."DETALLE_OC" MODIFY ("ID_OC" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."DETALLE_OC" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."DETALLE_OC" MODIFY ("ID_DETALLE_OC" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERFIL
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."PERFIL" ADD CONSTRAINT "PERFIL_PK" PRIMARY KEY ("ID_PERFIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSTAL"."PERFIL" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."PERFIL" MODIFY ("ID_PERFIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DETALLE_MENU
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."DETALLE_MENU" ADD CONSTRAINT "DETALLE_MENU_PK" PRIMARY KEY ("ID_DETALLE_MENU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSTAL"."DETALLE_MENU" MODIFY ("ID_MENU" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."DETALLE_MENU" MODIFY ("ID_DETALLE_CLIENTE" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."DETALLE_MENU" MODIFY ("ID_DETALLE_MENU" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table RUBRO
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."RUBRO" ADD CONSTRAINT "RUBRO_PK" PRIMARY KEY ("ID_RUBRO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSTAL"."RUBRO" MODIFY ("DESCRIPION" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."RUBRO" MODIFY ("ID_RUBRO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PROVEEDOR
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."PROVEEDOR" ADD CONSTRAINT "PROVEEDOR_PK" PRIMARY KEY ("ID_PROVEEDOR")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSTAL"."PROVEEDOR" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."PROVEEDOR" MODIFY ("ID_RUBRO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."PROVEEDOR" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."PROVEEDOR" MODIFY ("RUT" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."PROVEEDOR" MODIFY ("APELLIDO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."PROVEEDOR" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."PROVEEDOR" MODIFY ("ID_PROVEEDOR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table LOGIN
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."LOGIN" ADD CONSTRAINT "LOGIN_PK" PRIMARY KEY ("ID_USUARIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSTAL"."LOGIN" MODIFY ("ID_PERFIL" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."LOGIN" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."LOGIN" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."LOGIN" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."LOGIN" ADD CONSTRAINT "UNIQUE_CONSTRAINT_USERNAME" UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HOTEL
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."HOTEL" ADD CONSTRAINT "HOTEL_PK" PRIMARY KEY ("ID_HOTEL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSTAL"."HOTEL" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."HOTEL" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."HOTEL" MODIFY ("RUT" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."HOTEL" MODIFY ("NOMBRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HABITACION
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."HABITACION" ADD CONSTRAINT "HABITACION_PK" PRIMARY KEY ("ID_HABITACION")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSTAL"."HABITACION" MODIFY ("ID_ESTADO_HAB" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."HABITACION" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."HABITACION" MODIFY ("ID_TIPO_CAMA" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."HABITACION" MODIFY ("ID_HABITACION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."PRODUCTO" ADD CONSTRAINT "PRODUCTO_PK" PRIMARY KEY ("ID_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSTAL"."PRODUCTO" MODIFY ("STOCK" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."PRODUCTO" MODIFY ("PRECIO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."PRODUCTO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."PRODUCTO" MODIFY ("ID_DETALLE_PRODUCTO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."PRODUCTO" MODIFY ("ID_CATEGORIA" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."PRODUCTO" MODIFY ("ID_PRODUCTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TIPO_CAMA
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."TIPO_CAMA" ADD CONSTRAINT "TIPO_CAMA_PK" PRIMARY KEY ("TIPO_CAMA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSTAL"."TIPO_CAMA" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."TIPO_CAMA" MODIFY ("TIPO_CAMA" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EMPRESA
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."EMPRESA" MODIFY ("ID_HOTEL" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."EMPRESA" MODIFY ("ID_USUARIO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."EMPRESA" MODIFY ("ACTIVO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."EMPRESA" ADD CONSTRAINT "EMPRESA_PK" PRIMARY KEY ("ID_EMPRESA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSTAL"."EMPRESA" MODIFY ("TELEFONO" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."EMPRESA" MODIFY ("DIRECCION" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."EMPRESA" MODIFY ("RUT" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."EMPRESA" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."EMPRESA" MODIFY ("MAIL" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table ACCESORIO
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."ACCESORIO" ADD CONSTRAINT "ACCESORIO_PK" PRIMARY KEY ("ID_ACCESORIO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSTAL"."ACCESORIO" MODIFY ("NOMBRE" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."ACCESORIO" MODIFY ("ID_ACCESORIO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table DETALLE_PRODUCTO
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."DETALLE_PRODUCTO" ADD CONSTRAINT "DETALLE_PRODUCTO_PK" PRIMARY KEY ("ID_DETALLE_PRODUCTO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSTAL"."DETALLE_PRODUCTO" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."DETALLE_PRODUCTO" MODIFY ("ID_DETALLE_PRODUCTO" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table PERIODO_MENU
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."PERIODO_MENU" ADD CONSTRAINT "PERIODO_MENU_PK" PRIMARY KEY ("ID_PERIODO_MENU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOSTAL"."PERIODO_MENU" MODIFY ("ID_MENU" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."PERIODO_MENU" MODIFY ("DESCRIPCION" NOT NULL ENABLE);
  ALTER TABLE "HOSTAL"."PERIODO_MENU" MODIFY ("ID_PERIODO_MENU" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table CLIENTE
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."CLIENTE" ADD CONSTRAINT "ID_EMPRESA_FK1" FOREIGN KEY ("ID_EMPRESA")
	  REFERENCES "HOSTAL"."EMPRESA" ("ID_EMPRESA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLE_CLIENTE
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."DETALLE_CLIENTE" ADD CONSTRAINT "ID_CLIENTE_FK1" FOREIGN KEY ("ID_CLIENTE")
	  REFERENCES "HOSTAL"."CLIENTE" ("ID_CLIENTE") ENABLE;
  ALTER TABLE "HOSTAL"."DETALLE_CLIENTE" ADD CONSTRAINT "ID_HABITACION_FK1" FOREIGN KEY ("ID_HABITACION")
	  REFERENCES "HOSTAL"."HABITACION" ("ID_HABITACION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLE_FACTURA
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."DETALLE_FACTURA" ADD CONSTRAINT "ID_DETALLE_CLIENTE_FK2" FOREIGN KEY ("ID_DETALLE_CLIENTE")
	  REFERENCES "HOSTAL"."DETALLE_CLIENTE" ("ID_DETALLE_CLIENTE") ENABLE;
  ALTER TABLE "HOSTAL"."DETALLE_FACTURA" ADD CONSTRAINT "ID_FACTURA_FK1" FOREIGN KEY ("ID_FACTURA")
	  REFERENCES "HOSTAL"."FACTURA" ("ID_FACTURA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLE_MENU
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."DETALLE_MENU" ADD CONSTRAINT "ID_DETALLE_CLIENTE_FK1" FOREIGN KEY ("ID_DETALLE_CLIENTE")
	  REFERENCES "HOSTAL"."DETALLE_CLIENTE" ("ID_DETALLE_CLIENTE") ENABLE;
  ALTER TABLE "HOSTAL"."DETALLE_MENU" ADD CONSTRAINT "ID_MENU_FK1" FOREIGN KEY ("ID_MENU")
	  REFERENCES "HOSTAL"."MENU" ("ID_MENU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLE_OC
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."DETALLE_OC" ADD CONSTRAINT "ID_OC_FK1" FOREIGN KEY ("ID_OC")
	  REFERENCES "HOSTAL"."ORDEN_COMPRA" ("ID_OC") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DETALLE_PEDIDO
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."DETALLE_PEDIDO" ADD CONSTRAINT "ID_ORDEN_PEDIDO_FK2" FOREIGN KEY ("ID_ORDEN_PEDIDO")
	  REFERENCES "HOSTAL"."ORDEN_PEDIDO" ("ID_ORDEN_PEDIDO") ENABLE;
  ALTER TABLE "HOSTAL"."DETALLE_PEDIDO" ADD CONSTRAINT "ID_PRODUCTO_FK1" FOREIGN KEY ("ID_PRODUCTO")
	  REFERENCES "HOSTAL"."PRODUCTO" ("ID_PRODUCTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPLEADO
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."EMPLEADO" ADD CONSTRAINT "ID_HOTEL_FK2" FOREIGN KEY ("ID_HOTEL")
	  REFERENCES "HOSTAL"."HOTEL" ("ID_HOTEL") ENABLE;
  ALTER TABLE "HOSTAL"."EMPLEADO" ADD CONSTRAINT "ID_USUARIO_FK2" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "HOSTAL"."LOGIN" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table EMPRESA
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."EMPRESA" ADD CONSTRAINT "ID_HOTEL_FK1" FOREIGN KEY ("ID_HOTEL")
	  REFERENCES "HOSTAL"."HOTEL" ("ID_HOTEL") ENABLE;
  ALTER TABLE "HOSTAL"."EMPRESA" ADD CONSTRAINT "USUARIO_FK1" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "HOSTAL"."LOGIN" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FACTURA
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."FACTURA" ADD CONSTRAINT "ID_EMPRESA_FK2" FOREIGN KEY ("ID_EMPRESA")
	  REFERENCES "HOSTAL"."EMPRESA" ("ID_EMPRESA") ENABLE;
  ALTER TABLE "HOSTAL"."FACTURA" ADD CONSTRAINT "ID_ESTADO_FK1" FOREIGN KEY ("ID_ESTADO")
	  REFERENCES "HOSTAL"."ESTADO" ("ID_ESTADO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HAB_ACCESORIO
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."HAB_ACCESORIO" ADD CONSTRAINT "ID_ACCESORIO_FK1" FOREIGN KEY ("ID_ACCESORIO")
	  REFERENCES "HOSTAL"."ACCESORIO" ("ID_ACCESORIO") ENABLE;
  ALTER TABLE "HOSTAL"."HAB_ACCESORIO" ADD CONSTRAINT "ID_HABITACION_FK2" FOREIGN KEY ("ID_HABITACION")
	  REFERENCES "HOSTAL"."HABITACION" ("ID_HABITACION") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HABITACION
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."HABITACION" ADD CONSTRAINT "ID_ESTADO_HAB_FK1" FOREIGN KEY ("ID_ESTADO_HAB")
	  REFERENCES "HOSTAL"."ESTADO_HAB" ("ID_ESTADO_HAB") ENABLE;
  ALTER TABLE "HOSTAL"."HABITACION" ADD CONSTRAINT "ID_TIPO_CAMA_FK1" FOREIGN KEY ("ID_TIPO_CAMA")
	  REFERENCES "HOSTAL"."TIPO_CAMA" ("TIPO_CAMA") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table LOGIN
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."LOGIN" ADD CONSTRAINT "ID_PERFIL_FK1" FOREIGN KEY ("ID_PERFIL")
	  REFERENCES "HOSTAL"."PERFIL" ("ID_PERFIL") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table MENU
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."MENU" ADD CONSTRAINT "ID_TIPO_MENU_FK1" FOREIGN KEY ("ID_TIPO_MENU")
	  REFERENCES "HOSTAL"."TIPO_MENU" ("ID_TIPO_MENU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDEN_COMPRA
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."ORDEN_COMPRA" ADD CONSTRAINT "ID_EMPRESA_FK3" FOREIGN KEY ("ID_EMPRESA")
	  REFERENCES "HOSTAL"."EMPRESA" ("ID_EMPRESA") ENABLE;
  ALTER TABLE "HOSTAL"."ORDEN_COMPRA" ADD CONSTRAINT "ID_ESTADO_FK2" FOREIGN KEY ("ID_ESTADO")
	  REFERENCES "HOSTAL"."ESTADO" ("ID_ESTADO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table ORDEN_PEDIDO
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."ORDEN_PEDIDO" ADD CONSTRAINT "ID_EMPLEADO_FK1" FOREIGN KEY ("ID_EMPLEADO")
	  REFERENCES "HOSTAL"."EMPLEADO" ("ID_EMPLEADO") ENABLE;
  ALTER TABLE "HOSTAL"."ORDEN_PEDIDO" ADD CONSTRAINT "ID_ESTADO_FK3" FOREIGN KEY ("ID_ESTADO")
	  REFERENCES "HOSTAL"."ESTADO" ("ID_ESTADO") ENABLE;
  ALTER TABLE "HOSTAL"."ORDEN_PEDIDO" ADD CONSTRAINT "ID_PROVEEDOR_FK1" FOREIGN KEY ("ID_PROVEEDOR")
	  REFERENCES "HOSTAL"."PROVEEDOR" ("ID_PROVEEDOR") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PERIODO_MENU
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."PERIODO_MENU" ADD CONSTRAINT "ID_MENU_FK2" FOREIGN KEY ("ID_MENU")
	  REFERENCES "HOSTAL"."MENU" ("ID_MENU") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PRODUCTO
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."PRODUCTO" ADD CONSTRAINT "ID_CATEGORIA_FK1" FOREIGN KEY ("ID_CATEGORIA")
	  REFERENCES "HOSTAL"."CATEGORIA" ("ID_CATEGORIA") ENABLE;
  ALTER TABLE "HOSTAL"."PRODUCTO" ADD CONSTRAINT "ID_DETALLE_PRODUCTO_FK1" FOREIGN KEY ("ID_DETALLE_PRODUCTO")
	  REFERENCES "HOSTAL"."DETALLE_PRODUCTO" ("ID_DETALLE_PRODUCTO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table PROVEEDOR
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."PROVEEDOR" ADD CONSTRAINT "ID_RUBRO_FK1" FOREIGN KEY ("ID_RUBRO")
	  REFERENCES "HOSTAL"."RUBRO" ("ID_RUBRO") ENABLE;
  ALTER TABLE "HOSTAL"."PROVEEDOR" ADD CONSTRAINT "ID_USUARIO_FK1" FOREIGN KEY ("ID_USUARIO")
	  REFERENCES "HOSTAL"."LOGIN" ("ID_USUARIO") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table RECEPCION_PEDIDO
--------------------------------------------------------

  ALTER TABLE "HOSTAL"."RECEPCION_PEDIDO" ADD CONSTRAINT "ID_EMPLEADO_FK2" FOREIGN KEY ("ID_EMPLEADO")
	  REFERENCES "HOSTAL"."EMPLEADO" ("ID_EMPLEADO") ENABLE;
  ALTER TABLE "HOSTAL"."RECEPCION_PEDIDO" ADD CONSTRAINT "ID_ORDEN_PEDIDO_FK1" FOREIGN KEY ("ID_ORDEN_PEDIDO")
	  REFERENCES "HOSTAL"."ORDEN_PEDIDO" ("ID_ORDEN_PEDIDO") ENABLE;
--------------------------------------------------------
--  DDL for Trigger ACCESORIO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."ACCESORIO_TRG" 
BEFORE INSERT ON ACCESORIO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_ACCESORIO IS NULL THEN
      SELECT ACCESORIO_SEQ.NEXTVAL INTO :NEW.ID_ACCESORIO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."ACCESORIO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CATEGORIA_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."CATEGORIA_TRG" 
BEFORE INSERT ON CATEGORIA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_CATEGORIA IS NULL THEN
      SELECT CATEGORIA_SEQ.NEXTVAL INTO :NEW.ID_CATEGORIA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."CATEGORIA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger CLIENTE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."CLIENTE_TRG" 
BEFORE INSERT ON CLIENTE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_CLIENTE IS NULL THEN
      SELECT CLIENTE_SEQ.NEXTVAL INTO :NEW.ID_CLIENTE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."CLIENTE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DETALLE_CLIENTE_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."DETALLE_CLIENTE_TRG" 
BEFORE INSERT ON DETALLE_CLIENTE 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_DETALLE_CLIENTE IS NULL THEN
      SELECT DETALLE_CLIENTE_SEQ.NEXTVAL INTO :NEW.ID_DETALLE_CLIENTE FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."DETALLE_CLIENTE_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DETALLE_FACTURA_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."DETALLE_FACTURA_TRG" 
BEFORE INSERT ON DETALLE_FACTURA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_DETALLE_FACTURA IS NULL THEN
      SELECT DETALLE_FACTURA_SEQ.NEXTVAL INTO :NEW.ID_DETALLE_FACTURA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."DETALLE_FACTURA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DETALLE_MENU_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."DETALLE_MENU_TRG" 
BEFORE INSERT ON DETALLE_MENU 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_DETALLE_MENU IS NULL THEN
      SELECT DETALLE_MENU_SEQ.NEXTVAL INTO :NEW.ID_DETALLE_MENU FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."DETALLE_MENU_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DETALLE_OC_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."DETALLE_OC_TRG" 
BEFORE INSERT ON DETALLE_OC 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_DETALLE_OC IS NULL THEN
      SELECT DETALLE_OC_SEQ.NEXTVAL INTO :NEW.ID_DETALLE_OC FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."DETALLE_OC_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DETALLE_PEDIDO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."DETALLE_PEDIDO_TRG" 
BEFORE INSERT ON DETALLE_PEDIDO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_DETALLE_PEDIDO IS NULL THEN
      SELECT DETALLE_PEDIDO_SEQ.NEXTVAL INTO :NEW.ID_DETALLE_PEDIDO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."DETALLE_PEDIDO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DETALLE_PRODUCTO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."DETALLE_PRODUCTO_TRG" 
BEFORE INSERT ON DETALLE_PRODUCTO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_DETALLE_PRODUCTO IS NULL THEN
      SELECT DETALLE_PRODUCTO_SEQ.NEXTVAL INTO :NEW.ID_DETALLE_PRODUCTO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."DETALLE_PRODUCTO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EMPLEADO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."EMPLEADO_TRG" 
BEFORE INSERT ON EMPLEADO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_EMPLEADO IS NULL THEN
      SELECT EMPLEADO_SEQ.NEXTVAL INTO :NEW.ID_EMPLEADO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."EMPLEADO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger EMPRESA_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."EMPRESA_TRG" 
BEFORE INSERT ON EMPRESA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_EMPRESA IS NULL THEN
      SELECT EMPRESA_SEQ.NEXTVAL INTO :NEW.ID_EMPRESA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."EMPRESA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ESTADO_HAB_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."ESTADO_HAB_TRG" 
BEFORE INSERT ON ESTADO_HAB 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_ESTADO_HAB IS NULL THEN
      SELECT ESTADO_HAB_SEQ.NEXTVAL INTO :NEW.ID_ESTADO_HAB FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."ESTADO_HAB_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ESTADO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."ESTADO_TRG" 
BEFORE INSERT ON ESTADO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_ESTADO IS NULL THEN
      SELECT ESTADO_SEQ.NEXTVAL INTO :NEW.ID_ESTADO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."ESTADO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger FACTURA_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."FACTURA_TRG" 
BEFORE INSERT ON FACTURA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_FACTURA IS NULL THEN
      SELECT FACTURA_SEQ.NEXTVAL INTO :NEW.ID_FACTURA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."FACTURA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HAB_ACCESORIO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."HAB_ACCESORIO_TRG" 
BEFORE INSERT ON HAB_ACCESORIO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_HAB_ACCESORIO IS NULL THEN
      SELECT HAB_ACCESORIO_SEQ.NEXTVAL INTO :NEW.ID_HAB_ACCESORIO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."HAB_ACCESORIO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HABITACION_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."HABITACION_TRG" 
BEFORE INSERT ON HABITACION 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_HABITACION IS NULL THEN
      SELECT HABITACION_SEQ.NEXTVAL INTO :NEW.ID_HABITACION FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."HABITACION_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HOTEL_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."HOTEL_TRG" 
BEFORE INSERT ON HOTEL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    NULL;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."HOTEL_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HOTEL_TRG1
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."HOTEL_TRG1" 
BEFORE INSERT ON HOTEL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_HOTEL IS NULL THEN
      SELECT HOTEL_SEQ1.NEXTVAL INTO :NEW.ID_HOTEL FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."HOTEL_TRG1" ENABLE;
--------------------------------------------------------
--  DDL for Trigger LOGIN_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."LOGIN_TRG" 
BEFORE INSERT ON LOGIN 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_USUARIO IS NULL THEN
      SELECT LOGIN_SEQ.NEXTVAL INTO :NEW.ID_USUARIO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."LOGIN_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger MENU_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."MENU_TRG" 
BEFORE INSERT ON MENU 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_MENU IS NULL THEN
      SELECT MENU_SEQ.NEXTVAL INTO :NEW.ID_MENU FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."MENU_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ORDEN_COMPRA_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."ORDEN_COMPRA_TRG" 
BEFORE INSERT ON ORDEN_COMPRA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_OC IS NULL THEN
      SELECT ORDEN_COMPRA_SEQ.NEXTVAL INTO :NEW.ID_OC FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."ORDEN_COMPRA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger ORDEN_PEDIDO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."ORDEN_PEDIDO_TRG" 
BEFORE INSERT ON ORDEN_PEDIDO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_ORDEN_PEDIDO IS NULL THEN
      SELECT ORDEN_PEDIDO_SEQ.NEXTVAL INTO :NEW.ID_ORDEN_PEDIDO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."ORDEN_PEDIDO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PERFIL_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."PERFIL_TRG" 
BEFORE INSERT ON PERFIL 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_PERFIL IS NULL THEN
      SELECT PERFIL_SEQ.NEXTVAL INTO :NEW.ID_PERFIL FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."PERFIL_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PERIODO_MENU_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."PERIODO_MENU_TRG" 
BEFORE INSERT ON PERIODO_MENU 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_PERIODO_MENU IS NULL THEN
      SELECT PERIODO_MENU_SEQ.NEXTVAL INTO :NEW.ID_PERIODO_MENU FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."PERIODO_MENU_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PRODUCTO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."PRODUCTO_TRG" 
BEFORE INSERT ON PRODUCTO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_PRODUCTO IS NULL THEN
      SELECT PRODUCTO_SEQ.NEXTVAL INTO :NEW.ID_PRODUCTO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."PRODUCTO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger PROVEEDOR_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."PROVEEDOR_TRG" 
BEFORE INSERT ON PROVEEDOR 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_PROVEEDOR IS NULL THEN
      SELECT PROVEEDOR_SEQ.NEXTVAL INTO :NEW.ID_PROVEEDOR FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."PROVEEDOR_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RECEPCION_PEDIDO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."RECEPCION_PEDIDO_TRG" 
BEFORE INSERT ON RECEPCION_PEDIDO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_RECEPCION_PEDIDO IS NULL THEN
      SELECT RECEPCION_PEDIDO_SEQ.NEXTVAL INTO :NEW.ID_RECEPCION_PEDIDO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."RECEPCION_PEDIDO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger RUBRO_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."RUBRO_TRG" 
BEFORE INSERT ON RUBRO 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_RUBRO IS NULL THEN
      SELECT RUBRO_SEQ.NEXTVAL INTO :NEW.ID_RUBRO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."RUBRO_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TIPO_CAMA_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."TIPO_CAMA_TRG" 
BEFORE INSERT ON TIPO_CAMA 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.TIPO_CAMA IS NULL THEN
      SELECT TIPO_CAMA_SEQ.NEXTVAL INTO :NEW.TIPO_CAMA FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."TIPO_CAMA_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger TIPO_MENU_TRG
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HOSTAL"."TIPO_MENU_TRG" 
BEFORE INSERT ON TIPO_MENU 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.ID_TIPO_MENU IS NULL THEN
      SELECT TIPO_MENU_SEQ.NEXTVAL INTO :NEW.ID_TIPO_MENU FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HOSTAL"."TIPO_MENU_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Function FN_GET_GLOSA_ERROR
--------------------------------------------------------

  CREATE OR REPLACE FUNCTION "HOSTAL"."FN_GET_GLOSA_ERROR" RETURN VARCHAR2
AS

/***********************************************************************************************************************
   NAME:    FN_GET_GLOSA_ERROR
   PURPOSE: Funcion que retorna glosa de error, incluye stacktrace con nombre del SP y linea donde se produce el error

   REVISIONS:
   Ver          Date           Author                       Description
   ---------    ----------     -------------------          -------------------------------------------------------------
   X.X.X-X.X    DD/MM/YYYY     AUTOR DE LA FUNCION          1. Funcion que retorna detalles del error ocurrido

************************************************************************************************************************/

LV_BACKTRACE VARCHAR2(4000) := DBMS_UTILITY.format_error_backtrace;
LV_MENSAJE VARCHAR2(4000) := '';

BEGIN

    LV_MENSAJE := CONCAT(LV_BACKTRACE, SUBSTR(SQLERRM, 1, 255));

    RETURN SUBSTR(LV_MENSAJE, 1, 4000);

EXCEPTION
    WHEN OTHERS THEN
        RETURN NULL;
END FN_GET_GLOSA_ERROR;

/
--------------------------------------------------------
--  DDL for Procedure SP_ACTUALIZA_EMPRESA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "HOSTAL"."SP_ACTUALIZA_EMPRESA" (
  IN_EMPRESA IN NUMBER,
  IN_NOMBRE IN VARCHAR2,
  IN_DIRECCION IN VARCHAR2,
  IN_TELEFONO IN NUMBER,
  IN_MAIL IN VARCHAR2,
  OUT_GLOSA OUT VARCHAR2,
  OUT_ESTADO OUT NUMBER
) AS

/**************************************************************************************************************
   NAME:       	SP_ACTUALIZA_EMPRESA
   PURPOSE		ACTUALIZA DATOS EMPRESA

   REVISIONS:
   Ver          Date           Author                     Description
   ---------    ----------     -------------------        ----------------------------------------------
   0.1    		17/05/2020     MARCELA VERGARA            1. ACTUALIZA DATOS EMPRESA
   
***************************************************************************************************************/


BEGIN
    OUT_ESTADO := 0;
    OUT_GLOSA := 'SP_ACTUALIZA_EMPRESA ejecutado exitosamente';

    UPDATE HOSTAL.EMPRESA SET
      NOMBRE = IN_NOMBRE,
	  DIRECCION = IN_DIRECCION,
	  TELEFONO = IN_TELEFONO,
	  MAIL = IN_MAIL
      WHERE ID_EMPRESA = IN_EMPRESA;

    EXCEPTION
        WHEN OTHERS THEN
            OUT_ESTADO := -1;
            OUT_GLOSA := HOSTAL.FN_GET_GLOSA_ERROR;

END SP_ACTUALIZA_EMPRESA;

/
--------------------------------------------------------
--  DDL for Procedure SP_CREA_EMPRESA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "HOSTAL"."SP_CREA_EMPRESA" (
    IN_NOMBRE IN VARCHAR2,
    IN_RUT IN VARCHAR2,
    IN_DIRECCION IN VARCHAR2,
    IN_TELEFONO IN NUMBER,
    IN_MAIL IN VARCHAR2,
    IN_USERNAME IN VARCHAR2,
    IN_PASSWORD IN VARCHAR2,
    IN_PERIL IN NUMBER,
    IN_HOTEL IN NUMBER,    
    OUT_GLOSA OUT VARCHAR2,
    OUT_ESTADO OUT NUMBER,
    OUT_ID_SALIDA OUT NUMBER,
	OUT_ID_USUARIO OUT NUMBER
) AS

/**************************************************************************************************************
   NAME:       	SP_CREA_EMPRESA
   PURPOSE		CREA UNA EMPRESA

   REVISIONS:
   Ver          Date           Author                               Description
   ---------    ----------     -------------------                  ----------------------------------------------
   0.1.X-X.X    17/05/2020     MARCELA VERGARA       			1. CREA UN REGISTRO EN LA TABLA EMPRESA
   
   SE DEBEN AGREGAR TODAS LAS VERSIONES QUE Y NOMBRES DE LOS QUE TRABAJEN EN EL 
***************************************************************************************************************/

BEGIN
    OUT_ESTADO := 0;
    OUT_GLOSA := 'SP_CREA_EMPRESA ejecutado exitosamente';

    
	INSERT INTO HOSTAL.LOGIN(
    ID_USUARIO,
		USERNAME,
		PASSWORD,
		ID_PERFIL
	)
	 VALUES (
		HOSTAL.LOGIN_SEQ.NEXTVAL,
		IN_USERNAME,
		IN_PASSWORD,
		IN_PERIL
		
	 ) RETURNING ID_USUARIO INTO OUT_ID_USUARIO;
	
	INSERT INTO HOSTAL.EMPRESA(
        ID_EMPRESA,
        NOMBRE,
        RUT,
        DIRECCION,
        TELEFONO,
        MAIL,
        ID_USUARIO,
        ID_HOTEL
   )
    VALUES (
      HOSTAL.EMPRESA_SEQ.NEXTVAL,
      IN_NOMBRE,
      IN_RUT,
      IN_DIRECCION,
      IN_TELEFONO,
      IN_MAIL,
      OUT_ID_USUARIO,
      IN_HOTEL
    ) RETURNING ID_EMPRESA INTO OUT_ID_SALIDA;

    EXCEPTION
        WHEN OTHERS THEN
            OUT_ESTADO := -1;
            OUT_GLOSA := HOSTAL.FN_GET_GLOSA_ERROR;

END SP_CREA_EMPRESA;

/
--------------------------------------------------------
--  DDL for Procedure SP_DESACTIVA_EMPRESA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "HOSTAL"."SP_DESACTIVA_EMPRESA" (
  IN_EMPRESA IN NUMBER,
  IN_ACTIVO IN VARCHAR2,
  OUT_GLOSA OUT VARCHAR2,
  OUT_ESTADO OUT NUMBER
) AS


/**************************************************************************************************************
   NAME:       	SP_DESACTIVA_EMPRESA
   PURPOSE		DESACTIVA UNA EMPRESA

   REVISIONS:
   Ver          Date           Author                   Description
   ---------    ----------     -------------------      ----------------------------------------------
   0.2    		17/05/2020     MARCELA VERGARA       	1. DESACTIVA EMPRESA
   
***************************************************************************************************************/

BEGIN
    OUT_ESTADO := 0;
    OUT_GLOSA := 'SP_DESACTIVA_EMPRESA ejecutado exitosamente';

  UPDATE HOSTAL.EMPRESA SET
	ACTIVO = IN_ACTIVO
	WHERE ID_EMPRESA = IN_EMPRESA;

    EXCEPTION
        WHEN OTHERS THEN
            OUT_ESTADO := -1;
            OUT_GLOSA := HOSTAL.FN_GET_GLOSA_ERROR;

END SP_DESACTIVA_EMPRESA;

/
--------------------------------------------------------
--  DDL for Procedure SP_LEE_EMPRESA
--------------------------------------------------------
set define off;

  CREATE OR REPLACE PROCEDURE "HOSTAL"."SP_LEE_EMPRESA" (
  IN_EMPRESA IN NUMBER,
  OUT_GLOSA OUT VARCHAR2,
  OUT_ESTADO OUT NUMBER,
  OUT_NOMBRE_CURSOR OUT SYS_REFCURSOR  
) AS
/**************************************************************************************************************
   NAME:       	SP_LEE_EMPRESA
   PURPOSE		LEE DATOS EMPRESA

   REVISIONS:
   Ver          Date           Author                   Description
   ---------    ----------     -------------------      ----------------------------------------------
   0.1    		17/05/2020     MARCELA VERGARA          1. LEER INFO EMPRESA
   0.2    		17/05/2020     MARCELA VERGARA          2. LEER CAMPO ACTIVO
   
***************************************************************************************************************/
    

BEGIN
    OUT_ESTADO := 0;
    OUT_GLOSA := 'SP_LEE_EMPRESA ejecutado exitosamente';


    OPEN OUT_NOMBRE_CURSOR FOR
        SELECT
            E.NOMBRE,
            E.RUT,
            E.DIRECCION,
            E.TELEFONO,
            E.MAIL,
			E.ACTIVO,
            U.USERNAME,
			H.NOMBRE AS HOTEL
        FROM HOSTAL.EMPRESA E
		JOIN LOGIN U ON (E.ID_USUARIO = U.ID_USUARIO)
		JOIN HOTEL H ON (E.ID_HOTEL = H.ID_HOTEL)
		WHERE ID_EMPRESA = IN_EMPRESA;
  

    EXCEPTION
        WHEN OTHERS THEN
            OUT_ESTADO := -1;
            OUT_GLOSA := HOSTAL.FN_GET_GLOSA_ERROR;

END SP_LEE_EMPRESA;

/
